fixtures:
  repositories:
    limits: 'https://github.com/miguno/puppet-limits.git'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.1.0'
    supervisor: 'https://github.com/miguno/puppet-supervisor'
    remote_file: 'https://github.com/lwf/puppet-remote_file.git'
  symlinks:
    bookkeeper: "#{source_dir}"