name         'puppet-bookkeeper'
version      '0.0.1'
author       'Stephan Lohwasser'
license      'Apache 2.0'
project_page 'https://github.com/lowi-yeah/puppet-bookkeeper'
source       'https://github.com/lowi-yeah/puppet-bookkeeper'
summary      'A Wirbelsturm compatible module for managing and configuring Apache Bookkeeper bookies.'
description  'A Wirbelsturm compatible module for managing and configuring Apache Bookkeeper bookies.'
dependency   'puppetlabs/stdlib', '>= 3.0.0'
dependency   'puppetlabs/apt', '1.x'
